package com.letv.cdn.manager.pojo;

public class UserDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_domain.id
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_domain.user_id
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_domain.domain_tag
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    private String domainTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_domain.id
     *
     * @return the value of user_domain.id
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_domain.id
     *
     * @param id the value for user_domain.id
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_domain.user_id
     *
     * @return the value of user_domain.user_id
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_domain.user_id
     *
     * @param userId the value for user_domain.user_id
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_domain.domain_tag
     *
     * @return the value of user_domain.domain_tag
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    public String getDomainTag() {
        return domainTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_domain.domain_tag
     *
     * @param domainTag the value for user_domain.domain_tag
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    public void setDomainTag(String domainTag) {
        this.domainTag = domainTag == null ? null : domainTag.trim();
    }
}