package com.letv.cdn.monitor.pojo;

public class AlarmSettings {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_settings.id
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_settings.item
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    private String item;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_settings.max_value
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    private String maxValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_settings.sleep
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    private Byte sleep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_settings.times
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    private Byte times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_settings.description
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_settings.id
     *
     * @return the value of alarm_settings.id
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_settings.id
     *
     * @param id the value for alarm_settings.id
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_settings.item
     *
     * @return the value of alarm_settings.item
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_settings.item
     *
     * @param item the value for alarm_settings.item
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public void setItem(String item) {
        this.item = item == null ? null : item.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_settings.max_value
     *
     * @return the value of alarm_settings.max_value
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public String getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_settings.max_value
     *
     * @param maxValue the value for alarm_settings.max_value
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public void setMaxValue(String maxValue) {
        this.maxValue = maxValue == null ? null : maxValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_settings.sleep
     *
     * @return the value of alarm_settings.sleep
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public Byte getSleep() {
        return sleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_settings.sleep
     *
     * @param sleep the value for alarm_settings.sleep
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public void setSleep(Byte sleep) {
        this.sleep = sleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_settings.times
     *
     * @return the value of alarm_settings.times
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public Byte getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_settings.times
     *
     * @param times the value for alarm_settings.times
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public void setTimes(Byte times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_settings.description
     *
     * @return the value of alarm_settings.description
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_settings.description
     *
     * @param description the value for alarm_settings.description
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}