package com.letv.cdn.monitor.pojo;

import java.util.ArrayList;
import java.util.List;

public class ClusterSettingsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    protected int[] limit = new int[] {-1, -1};

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public ClusterSettingsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public void setLimitValue1(int val) {
        this.limit[0] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public void setLimitValue2(int val) {
        this.limit[1] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public int getLimitValue1() {
        return this.limit[0];
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public int getLimitValue2() {
        return this.limit[1];
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andClusterIsNull() {
            addCriterion("cluster is null");
            return (Criteria) this;
        }

        public Criteria andClusterIsNotNull() {
            addCriterion("cluster is not null");
            return (Criteria) this;
        }

        public Criteria andClusterEqualTo(String value) {
            addCriterion("cluster =", value, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterNotEqualTo(String value) {
            addCriterion("cluster <>", value, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterGreaterThan(String value) {
            addCriterion("cluster >", value, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterGreaterThanOrEqualTo(String value) {
            addCriterion("cluster >=", value, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterLessThan(String value) {
            addCriterion("cluster <", value, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterLessThanOrEqualTo(String value) {
            addCriterion("cluster <=", value, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterLike(String value) {
            addCriterion("cluster like", value, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterNotLike(String value) {
            addCriterion("cluster not like", value, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterIn(List<String> values) {
            addCriterion("cluster in", values, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterNotIn(List<String> values) {
            addCriterion("cluster not in", values, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterBetween(String value1, String value2) {
            addCriterion("cluster between", value1, value2, "cluster");
            return (Criteria) this;
        }

        public Criteria andClusterNotBetween(String value1, String value2) {
            addCriterion("cluster not between", value1, value2, "cluster");
            return (Criteria) this;
        }

        public Criteria andIpsIsNull() {
            addCriterion("ips is null");
            return (Criteria) this;
        }

        public Criteria andIpsIsNotNull() {
            addCriterion("ips is not null");
            return (Criteria) this;
        }

        public Criteria andIpsEqualTo(String value) {
            addCriterion("ips =", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsNotEqualTo(String value) {
            addCriterion("ips <>", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsGreaterThan(String value) {
            addCriterion("ips >", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsGreaterThanOrEqualTo(String value) {
            addCriterion("ips >=", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsLessThan(String value) {
            addCriterion("ips <", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsLessThanOrEqualTo(String value) {
            addCriterion("ips <=", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsLike(String value) {
            addCriterion("ips like", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsNotLike(String value) {
            addCriterion("ips not like", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsIn(List<String> values) {
            addCriterion("ips in", values, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsNotIn(List<String> values) {
            addCriterion("ips not in", values, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsBetween(String value1, String value2) {
            addCriterion("ips between", value1, value2, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsNotBetween(String value1, String value2) {
            addCriterion("ips not between", value1, value2, "ips");
            return (Criteria) this;
        }

        public Criteria andProcessKeyIsNull() {
            addCriterion("process_key is null");
            return (Criteria) this;
        }

        public Criteria andProcessKeyIsNotNull() {
            addCriterion("process_key is not null");
            return (Criteria) this;
        }

        public Criteria andProcessKeyEqualTo(String value) {
            addCriterion("process_key =", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyNotEqualTo(String value) {
            addCriterion("process_key <>", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyGreaterThan(String value) {
            addCriterion("process_key >", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyGreaterThanOrEqualTo(String value) {
            addCriterion("process_key >=", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyLessThan(String value) {
            addCriterion("process_key <", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyLessThanOrEqualTo(String value) {
            addCriterion("process_key <=", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyLike(String value) {
            addCriterion("process_key like", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyNotLike(String value) {
            addCriterion("process_key not like", value, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyIn(List<String> values) {
            addCriterion("process_key in", values, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyNotIn(List<String> values) {
            addCriterion("process_key not in", values, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyBetween(String value1, String value2) {
            addCriterion("process_key between", value1, value2, "processKey");
            return (Criteria) this;
        }

        public Criteria andProcessKeyNotBetween(String value1, String value2) {
            addCriterion("process_key not between", value1, value2, "processKey");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("valid is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("valid is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Byte value) {
            addCriterion("valid =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Byte value) {
            addCriterion("valid <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Byte value) {
            addCriterion("valid >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Byte value) {
            addCriterion("valid >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Byte value) {
            addCriterion("valid <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Byte value) {
            addCriterion("valid <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Byte> values) {
            addCriterion("valid in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Byte> values) {
            addCriterion("valid not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Byte value1, Byte value2) {
            addCriterion("valid between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Byte value1, Byte value2) {
            addCriterion("valid not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andRebootIsNull() {
            addCriterion("reboot is null");
            return (Criteria) this;
        }

        public Criteria andRebootIsNotNull() {
            addCriterion("reboot is not null");
            return (Criteria) this;
        }

        public Criteria andRebootEqualTo(Byte value) {
            addCriterion("reboot =", value, "reboot");
            return (Criteria) this;
        }

        public Criteria andRebootNotEqualTo(Byte value) {
            addCriterion("reboot <>", value, "reboot");
            return (Criteria) this;
        }

        public Criteria andRebootGreaterThan(Byte value) {
            addCriterion("reboot >", value, "reboot");
            return (Criteria) this;
        }

        public Criteria andRebootGreaterThanOrEqualTo(Byte value) {
            addCriterion("reboot >=", value, "reboot");
            return (Criteria) this;
        }

        public Criteria andRebootLessThan(Byte value) {
            addCriterion("reboot <", value, "reboot");
            return (Criteria) this;
        }

        public Criteria andRebootLessThanOrEqualTo(Byte value) {
            addCriterion("reboot <=", value, "reboot");
            return (Criteria) this;
        }

        public Criteria andRebootIn(List<Byte> values) {
            addCriterion("reboot in", values, "reboot");
            return (Criteria) this;
        }

        public Criteria andRebootNotIn(List<Byte> values) {
            addCriterion("reboot not in", values, "reboot");
            return (Criteria) this;
        }

        public Criteria andRebootBetween(Byte value1, Byte value2) {
            addCriterion("reboot between", value1, value2, "reboot");
            return (Criteria) this;
        }

        public Criteria andRebootNotBetween(Byte value1, Byte value2) {
            addCriterion("reboot not between", value1, value2, "reboot");
            return (Criteria) this;
        }

        public Criteria andCmdIsNull() {
            addCriterion("cmd is null");
            return (Criteria) this;
        }

        public Criteria andCmdIsNotNull() {
            addCriterion("cmd is not null");
            return (Criteria) this;
        }

        public Criteria andCmdEqualTo(String value) {
            addCriterion("cmd =", value, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdNotEqualTo(String value) {
            addCriterion("cmd <>", value, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdGreaterThan(String value) {
            addCriterion("cmd >", value, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdGreaterThanOrEqualTo(String value) {
            addCriterion("cmd >=", value, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdLessThan(String value) {
            addCriterion("cmd <", value, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdLessThanOrEqualTo(String value) {
            addCriterion("cmd <=", value, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdLike(String value) {
            addCriterion("cmd like", value, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdNotLike(String value) {
            addCriterion("cmd not like", value, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdIn(List<String> values) {
            addCriterion("cmd in", values, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdNotIn(List<String> values) {
            addCriterion("cmd not in", values, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdBetween(String value1, String value2) {
            addCriterion("cmd between", value1, value2, "cmd");
            return (Criteria) this;
        }

        public Criteria andCmdNotBetween(String value1, String value2) {
            addCriterion("cmd not between", value1, value2, "cmd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cluster_settings
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 12 15:58:04 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cluster_settings
     *
     * @mbggenerated Thu Mar 12 15:58:04 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}