package com.letv.cdn.monitor.dao;

import com.letv.cdn.monitor.pojo.AlarmSettings;
import com.letv.cdn.monitor.pojo.AlarmSettingsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlarmSettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    int countByExample(AlarmSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    int deleteByExample(AlarmSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    int insert(AlarmSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    int insertSelective(AlarmSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    List<AlarmSettings> selectByExample(AlarmSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    AlarmSettings selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    int updateByExampleSelective(@Param("record") AlarmSettings record, @Param("example") AlarmSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    int updateByExample(@Param("record") AlarmSettings record, @Param("example") AlarmSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    int updateByPrimaryKeySelective(AlarmSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_settings
     *
     * @mbggenerated Mon Mar 09 14:17:23 CST 2015
     */
    int updateByPrimaryKey(AlarmSettings record);
}