package com.letv.cdn.manager.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.letv.cdn.manager.pojo.UserDomain;
import com.letv.cdn.manager.pojo.UserDomainExample;

public interface UserDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    int countByExample(UserDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    int deleteByExample(UserDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    int insert(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    int insertSelective(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    List<UserDomain> selectByExample(UserDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    UserDomain selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserDomain record, @Param("example") UserDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    int updateByExample(@Param("record") UserDomain record, @Param("example") UserDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    int updateByPrimaryKeySelective(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Thu Sep 11 16:38:32 CST 2014
     */
    int updateByPrimaryKey(UserDomain record);
}